
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata = {
  title: 'DPWOOD Store',
  description: 'Cửa hàng nội thất và các sản phẩm từ gỗ cao cấp.',
  openGraph: {
    title: 'DPWOOD Store',
    description: 'Cửa hàng nội thất và các sản phẩm từ gỗ cao cấp.',
    url: 'https://dpwood.store',
    siteName: 'DPWOOD',
    images: [
      {
        url: 'https://dpwood.store/thumbnail.jpg', // Đường dẫn tới ảnh của bạn
        width: 1200,
        height: 630,
        alt: 'DPWOOD Store Thumbnail',
      },
    ],
    locale: 'vi_VN',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
